server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        #  USER SERVICE
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        #  PRODUCT SERVICE 
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        #  INVENTORY SERVICE 
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**

        # ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# DEBUG 
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
