jwt:
  secret: "mySuperSecretKeyForJwtGeneration1234567890"
  expiration: 3600000 # 1 hour in milliseconds

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: "Kunal@123"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
